### ISSUE TITLE
Тестер

### ISSUE THREAD

**Issue by tursunbaevz** [ESDP-2016-1/imho.kg#19]
# Что нужно сделать

Подготовить доклад на тему "Тест"
Узнать с каким браузером совместим
# Как это сделать

найти материалы данной темы и изучить 
# Критерии приемки
# Срок выполнения

Оценочное время: 3 дня
Фактическое время: 3 дня

**Comment by aibekak** [comment]
# Вся инфа в вики нашего проекта
