### ISSUE TITLE
Создать базовый функционал регистрации пользователя

### ISSUE THREAD

**Issue by sn0w1eo** [ESDP-2016-1/imho.kg#2]
# Что нужно сделать

Подключаем и конфигурируем gem devise
Подключаем Bootstrap
Делаем email подтверждению, но пока в development моде.
# Зачем это делать

Для авторизации/аутентификации пользователей
Для того чтобы у нас была шапка для сайта и чтоб выглядела лучше.
Для того чтобы зарегестрироваться и пользоваться сайтом нужно email подтверждения. 
# Как это сделать

Создаём модель пользователя
Устанавливаем/настраиваем gem devise
Мы не будем подключать gem, мы в проект закинем bootstrapовские файлы
Мы переконфигурироваем devise чтоб он отправлял email confirmation на почту регистратора, и нужен нам gem mailcatcher чтобы отлавливать отправленные почты.  
# Критерии приемки

``` gherkin
Допустим я захожу на сайт
И авторизируюсь для выполнения каких либо действий
```

**Comment by aibekak** [comment]
Делали 3 часа
