### ISSUE TITLE
Создать фикстуры пользователей для сайта

### ISSUE THREAD

**Issue by vasview** [ESDP-2016-1/imho.kg#31]
# Что нужно сделать

Создать фикстуры пользователей для сайта, с ролями "пользователь", "агент компании", "модератор", "администратор сайта"
# Зачем это делать

Для того, чтобы иметь различных пользователей для проверки их функциональности на сайте. 
# Как это сделать

(подумать, как можно улучшить код для фикстуры)

В "seeds.rb" в разделе USERS написать:

User.create(name:                  'user',
              email:                 'user@example.com',
              password:              '123456',
              password_confirmation: '123456',
              dob:                   '1994/06/14',
              gender_id:             1,
              city_id:               2,
              active:                true,
              role_id:               1)

  User.create(name:                  'agent',
              email:                 'agent@example.com',
              password:              '123456',
              password_confirmation: '123456',
              dob:                   '1994/06/14',
              gender_id:             1,
              city_id:               2,
              active:                true,
              role_id:               2)

User.create(name:                  'moder',
              email:                 'admin@example.com',
              password:              '123456',
              password_confirmation: '123456',
              dob:                   '1994/06/14',
              gender_id:             1,
              city_id:               2,
              active:                true,
              role_id:               3)

  User.create(name:                  'admin',
              email:                 'min@example.com',
              password:              '123456',
              password_confirmation: '123456',
              dob:                   '1994/06/14',
              gender_id:             1,
              city_id:               2,
              active:                true,
              role_id:               4)

Прогнать миграцию rake db:migrate:reset rake db:seed
# Критерии приемки

Допустим я открываю сайт
и захожу на сайт под учетной записью администратора
и перехожу в раздел "Пользователи" административной панели
и вижу созданных пользователей с соответствующими ролями.
# Сроки исполнения

Оценочное время: 1час
Фактическое время:

**Comment by sn0w1eo** [comment]
Оптимизировано #53
