### ISSUE TITLE
Создать карточку компании для отображения на главной странице

### ISSUE THREAD

**Issue by vasview** [ESDP-2016-1/imho.kg#32]
# Что нужно сделать

Сверстать карточку компании для отображения краткой информации о компании на главной странице.
# Зачем это делать

Для отображения карточек компании на главной странице сайта.
# Как это сделать

Создать паршиал _mini_company_card.html.erb в директории /views/pages. 
В этом паршиале создать форму для отображения необходимых данных о компании. Сделать верстку карточки согласно дизайна.

Подлключить паршиал для отображения на главной странице.

# Критерии приемки

Допустим  я открываю сайт
и на главной странице вижу карточку компании
# Сроки исполнения

Оценочное время: 5часов
Фактическое время: 5 часов

**Comment by aibekak** [comment]
сделал вьюху на глав странице

**Comment by sn0w1eo** [comment]
Произведен рефакторинг #53
