### ISSUE TITLE
Cоздать CRUD для сущности users

### ISSUE THREAD

**Issue by vasview** [ESDP-2016-1/imho.kg#39]
# Что нужно сделать

Создать контроллер и экшены для управления сущностью пользователя.
# Зачем это делать

Для того, чтобы пользователь мог редактировать свои учетные данные. Чтобы другие пользователи сайта могли просматривать профиль пользователя.
# Как это сделать

Создать контроллер Users с методами show, edit, update, destroy.
Сверстать личную страничку пользователя согласно дизайна сайта.
# Критерии приемки

Допустим  я открываю сайт
и на главной странице нажимаю кнопку "Вход"
и вхожу учетные данные пользователя в окно входа
и нажимаю кнопку "Войти"
и после успешного входа вижу аватар пользователя в правом верхнем углу меню
и нажимаю на выпадающую стрелку для перехода на профиль пользователя.
# Сроки исполнения

Оценочное время: 5часов
Фактическое время:

**Comment by aibekak** [comment]
need to enhance later on
