### ISSUE TITLE
Меняем scope для devise чтобы можно было создать свои контроллеры users

### ISSUE THREAD

**Issue by aibekak** [ESDP-2016-1/imho.kg#40]
# Что нужно сделать

Поменять scope для devise чтобы пути не путались при создании users_controllers.rb
# Зачем это делать

Для того, чтобы можно было сделать страничку пользователя и редактирование.
# Как это сделать

Нужно дозаписать в файле config/routes.rb `devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}, :path => 'auth'`   
# Критерии приемки

если запустить `rake routes` вижу что наши пути по devise изменились на `auth/sign_in` итд.
# Сроки исполнения

Оценочное время: 15мин
Фактическое время: 15мин

**Comment by sn0w1eo** [comment]
Реализован полностью в #53 Рефакторинг
