### ISSUE TITLE
Need gem faker

### ISSUE THREAD

**Issue by aibekak** [ESDP-2016-1/imho.kg#46]
# Что нужно сделать
Подключить gem 'faker', и дописать в сиидах побольше комментарии. 

# Зачем это делать
Для того чтобы можно было поработать над деревом коментарии.

# Как это сделать
Дописать в gemfile ```gem 'faker'``` запустить в терминале bundle.
Создать в побольше комментарии в файле ```seeds.rb``` используя gem 'faker' 

# Критерии приемки

# Сроки исполнения

Оценочное время: 1час
Фактическое время:

**Comment by sn0w1eo** [comment]
Переписаны seeds.rb #53 Рефакторинг
