### ISSUE TITLE
Добавить отображение количество негативных и позитивных отзывов на главной странице

### ISSUE THREAD

**Issue by vasview** [ESDP-2016-1/imho.kg#47]
# Что нужно сделать

Добавить количество негативных и позитивных отзывов на главной странице. 
# Зачем это делать

Для того, чтобы пользователь мог видеть общее к-во негативных и позитивных отзывов на сайте.  
# Как это сделать

Добавить во вьюшке pages/index.html.erb код:
<span><%= Ucomment.where(positive: false).count %></span> для отображения негативных отзывов
и 
<%= Ucomment.where(positive: true).count %></span> для отображения позитивных отзывов.
# Критерии приемки

Допустим я захожу на главную страницу сайта
и вижу под шапкой сайта общее к-во негативных и позитивных отзывов.
и добавляю негативный отзыв
и перехожу на главную страницу сайта
и вижу что негативных отзывов стало на один больше.
# Сроки исполнения

Оценочное время: 10 минут
Фактическое время: 10 минут

**Comment by sn0w1eo** [comment]
Реализовано #53 Рефакторинг
