### ISSUE TITLE
Добавить отображение к-во позитивных и негативных отзывов к карточке компании

### ISSUE THREAD

**Issue by vasview** [ESDP-2016-1/imho.kg#48]
# Что нужно сделать

Добавить отображение количество негативных и позитивных отзывов к карточке компании на главной странице. 

# Зачем это делать

Для того, чтобы пользователь мог видеть общее к-во негативных и позитивных отзывов по каждой компании.  
# Как это сделать

Добавить во вьюшке pages/index.html.erb код:
<span><%= company.ucomments.where(positive: false).count %></span> для отображения негативных отзывов
и 
<span><%= company.ucomments.where(positive: true).count %></span> для отображения позитивных отзывов.

подправить pages.scss файл, для отображение данных на странице.
# Критерии приемки

Допустим я захожу на главную страницу сайта
и вижу на карточке компании общее к-во негативных и позитивных отзывов.
и добавляю негативный отзыв
и перехожу на главную страницу сайта
и вижу что негативных отзывов стало на один больше.
# Сроки исполнения

Оценочное время: 30 минут
Фактическое время: 30 минут

**Comment by zmanlynx** [comment]
Реализовано #53 Рефакторинг

**Comment by sn0w1eo** [comment]
Реализовано #53 Рефакторинг
