### ISSUE TITLE
Доработка БД для User

### ISSUE THREAD

**Issue by FlimFlix** [ESDP-2016-1/imho.kg#9]
# Что нужно сделать

Добавить следующие поля: 
- role_id:integer
- fullname:string
- active:boolean(default_false) - после email confirmation меняется на true
- city_id:integer
- gender_id:integer

Удалить поле: sex:integer.
# Зачем это делать

Нужны роли для каждого юзера - агент компании или обычный пользователь, админ или модератор.
Для отображения имени пользователя на своей странице.
Для регулировки авторизации активности пользователя.
Для указания местоположения пользователей и компаний.
# Как это сделать

Используем терминал:

```
add column to table User role_id:integer, fullname:string, active:boolean, city_id:integer, gender_id:integer
remove_column :user, :sex
```

Прогнать миграцию `rake db:migrate`
# Критерии приемки

``` gherkin
Допустим я открываю файл "schema.rb"
И вижу следующие новые поля:
| поле | тип |
| role_id  | integer|
| fullname| string   |
| active | boolean |
| city_id | integer |
| gender_id | integer |
```
# Сроки выполнения

Оценочное время: 2 часа.
Фактическое время: 30мин

**Comment by vasview** [comment]
Нужно создать Role model и потом можно будет добавить поле role_id в модель User.
